// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv1MdNQnLMs6rM8sLNctmqFCp9lVh7jNY',
    appId: '1:891340777842:web:c486cfde7f68dfaf4155eb',
    messagingSenderId: '891340777842',
    projectId: 'raksha-setu-324f3',
    authDomain: 'raksha-setu-324f3.firebaseapp.com',
    storageBucket: 'raksha-setu-324f3.firebasestorage.app',
    measurementId: 'G-4Q026NCX2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-oKAODkZtal81BhCsFLyb3pp4nU5t7Y',
    appId: '1:891340777842:android:ddc675cd08217f214155eb',
    messagingSenderId: '891340777842',
    projectId: 'raksha-setu-324f3',
    storageBucket: 'raksha-setu-324f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO1WT5vd1WuuEJqIP11Ghcs4zogbP5t8Q',
    appId: '1:891340777842:ios:44b47b8c9c0120c54155eb',
    messagingSenderId: '891340777842',
    projectId: 'raksha-setu-324f3',
    storageBucket: 'raksha-setu-324f3.firebasestorage.app',
    iosBundleId: 'com.example.rakshaSetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO1WT5vd1WuuEJqIP11Ghcs4zogbP5t8Q',
    appId: '1:891340777842:ios:44b47b8c9c0120c54155eb',
    messagingSenderId: '891340777842',
    projectId: 'raksha-setu-324f3',
    storageBucket: 'raksha-setu-324f3.firebasestorage.app',
    iosBundleId: 'com.example.rakshaSetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv1MdNQnLMs6rM8sLNctmqFCp9lVh7jNY',
    appId: '1:891340777842:web:8020d121fa5a40954155eb',
    messagingSenderId: '891340777842',
    projectId: 'raksha-setu-324f3',
    authDomain: 'raksha-setu-324f3.firebaseapp.com',
    storageBucket: 'raksha-setu-324f3.firebasestorage.app',
    measurementId: 'G-VLYB5HL04W',
  );
}
